src/SprykerSdk/Zed/Integrator/Business/Manifest/ManifestReader.php
src/SprykerSdk/Zed/Integrator/Communication/Plugin/Composer/InstallerComposerPlugin.php

https://spryker.atlassian.net/browse/TE-7965

TE-7965 fixed a version and travis issues

---

docs/manifest-types.md
src/Builder/ClassModifier/CommonClassModifier.php
src/Builder/Exception/LiteralValueParsingException.php
src/ManifestStrategy/ConfigureEnvManifestStrategy.php
tests/SprykerSdkTest/Integrator/BaseTestCase.php
tests/SprykerSdkTest/Integrator/Builder/ClassLoader/ClassLoaderTest.php
tests/SprykerSdkTest/Integrator/Builder/ClassModifier/ClassModifierTest.php
tests/_tests_files/test_integrator_config_module_class_modifier.php
tests/_tests_files/test_integrator_configure_module.php

https://spryker.atlassian.net/browse/TE-10899

TE-10889 added literal value processing

---

.github/workflows/ci.yml
README.md

Add code coverage badge to README.md

Add code coverage badge

---

docs/manifest-types.md

Ticket: https://spryker.atlassian.net/browse/PPLUS-1501

PPLUS-1501: Update documentation

---

src/Common/UtilText/Filter/CamelCaseToDash.php
src/ManifestStrategy/UnwirePluginManifestStrategy.php
tests/_data/manifests/src/integrator-manifests-master/Spryker/TestIntegratorUnwirePlugin/1.0.3/installer-manifest.json

Ticket: https://spryker.atlassian.net/browse/PPLUS-1334
Change log: 
* Covered not-existed files in UnwirePluginStrategy

PPLUS-1334: Provide patches & minors automatically: handle non-existent files

---

src/Builder/ArgumentBuilder/ArgumentBuilder.php
src/Builder/ClassMetadataBuilder/ClassMetadataBuilder.php
tests/_data/manifests/src/integrator-manifests-master/Spryker/TestIntegratorWirePlugin/1.0.2/installer-manifest.json
tests/_data/tests_files/test_integrator_wire_plugin_dependency_provider.php

Ticket: https://spryker.atlassian.net/browse/PPLUS-1869

PPLUS-1869: Allow array as type for arguments

---

src/Builder/Visitor/RemoveMethodVisitor.php
tests/_data/manifests/src/integrator-manifests-master/Spryker/TestIntegratorUnwirePlugin/1.0.3/installer-manifest.json
tests/_data/project_mock/src/Pyz/Zed/TestIntegratorUnwirePlugin/TestIntegratorUnwirePluginDependencyProvider.php

https://spryker.atlassian.net/browse/PPLUS-1766

PPLUS-1766 fix single plugin registration

---

src/Builder/Visitor/RemoveMethodVisitor.php
tests/_data/manifests/src/integrator-manifests-master/Spryker/TestIntegratorUnwirePlugin/1.0.3/installer-manifest.json
tests/_data/project_mock/src/Pyz/Zed/TestIntegratorUnwirePlugin/TestIntegratorUnwirePluginDependencyProvider.php

This PR contains the test that reproduces the uncovered scenario. Please do not merge this PR until the scenario will be covered.

PPLUS-1766: Add test for unwire manifest of single plugin scenario

---

docs/manifest-types.md
src/Builder/Visitor/AddPluginToPluginListVisitor.php
src/Builder/Visitor/RemovePluginFromPluginListVisitor.php
src/Helper/ClassHelper.php
tests/SprykerSdkTest/Integrator/IntegratorFacadeTest.php
tests/_data/manifests/src/integrator-manifests-master/Spryker/TestIntegratorUnwirePlugin/1.0.3/installer-manifest.json
tests/_data/manifests/src/integrator-manifests-master/Spryker/TestIntegratorWirePlugin/1.0.2/installer-manifest.json
tests/_data/project_mock/src/Pyz/Zed/TestIntegratorUnwirePlugin/TestIntegratorUnwirePluginDependencyProvider.php
tests/_data/project_mock/src/Pyz/Zed/TestIntegratorWirePlugin/TestIntegratorWirePluginDependencyProvider.php
tests/_data/project_mock/src/Pyz/Zed/TestIntegratorWirePlugin/TestParentIntegratorWirePluginDependencyProvider.php
tests/_data/tests_files/test_integrator_unwire_console.php
tests/_data/tests_files/test_integrator_unwire_plugin_dependency_provider.php
tests/_data/tests_files/test_integrator_wire_console.php
tests/_data/tests_files/test_integrator_wire_plugin_dependency_provider.php

https://spryker.atlassian.net/browse/PPLUS-1759
- Covered adding a plugin with the condition.
- Covered adding a plugin with the condition if a method doesn't exist.
- Covered removing a plugin with the condition.

PPLUS-1759: Extend tests for plugin registration with conditions

---

docs/manifest-types.md
src/Builder/ClassMetadataBuilder/ClassMetadataBuilder.php
src/Builder/ClassModifier/ClassInstance/Wire/WireClassInstanceModifier.php
src/Builder/ClassModifier/ClassInstanceModifierStrategy/Wire/ReturnArrayWireClassInstanceModifierStrategy.php
src/Builder/Visitor/AddMethodCallToCallListVisitor.php
src/Executor/ManifestExecutor.php
src/IntegratorConfig.php
src/ManifestStrategy/WirePluginManifestStrategy.php
src/Transfer/CallMetadataTransfer.php
src/Transfer/ClassMetadataTransfer.php
tests/_data/manifests/src/integrator-manifests-master/Spryker/TestIntegratorWirePlugin/1.0.2/installer-manifest.json
tests/_data/project_mock/src/Pyz/Zed/TestIntegratorWirePlugin/TestIntegratorWirePluginDependencyProvider.php
tests/_data/tests_files/test_integrator_wire_plugin_dependency_provider.php

Ticket: https://spryker.atlassian.net/browse/PPLUS-1882
Change log: 
* Added applying `call` section for WirePlugin strategy

PPLUS-1758: Implementation wire integration

---

tests/_data/manifests/src/integrator-manifests-master/Spryker/TestIntegratorConfigureEnv/1.0.4/installer-manifest.json
tests/_data/project_mock/config/Shared/config_default.php
tests/_data/project_mock/src/Pyz/Client/TestIntegratorAddConfigArrayElement/TestIntegratorAddConfigArrayElementConfig.php
tests/_data/tests_files/test_integrator_add_config_array_element_config.php
tests/_data/tests_files/test_integrator_configure_env.php
tests/_data/tests_files/test_integrator_configure_env_choices.php

Few tests for IS state of constant rewrite behavior

Add tests for constant rewrite behavior

---

src/Builder/Visitor/AddPluginToPluginListVisitor.php
tests/SprykerSdkTest/Integrator/IntegratorFacadeTest.php
tests/_data/manifests/src/integrator-manifests-master/Spryker/TestIntegratorUnwirePlugin/1.0.3/installer-manifest.json
tests/_data/manifests/src/integrator-manifests-master/Spryker/TestIntegratorWirePlugin/1.0.2/installer-manifest.json
tests/_data/project_mock/src/Pyz/Zed/TestIntegratorUnwirePlugin/ParentTestIntegratorUnwirePluginDependencyProvider.php
tests/_data/project_mock/src/Pyz/Zed/TestIntegratorUnwirePlugin/TestIntegratorUnwirePluginDependencyProvider.php
tests/_data/project_mock/src/Pyz/Zed/TestIntegratorWirePlugin/TestIntegratorWirePluginDependencyProvider.php
tests/_data/tests_files/test_integrator_unwire_plugin_dependency_provider.php
tests/_data/tests_files/test_integrator_wire_plugin_dependency_provider.php

https://spryker.atlassian.net/browse/PPLUS-1761

SDK-1761: Wire, unwire plugin to array structure

---

src/Builder/Visitor/AddMethodCallToCallListVisitor.php
src/ManifestStrategy/WirePluginManifestStrategy.php
tests/_data/manifests/src/integrator-manifests-master/Spryker/TestIntegratorWirePlugin/1.0.2/installer-manifest.json
tests/_data/tests_files/test_integrator_wire_plugin_dependency_provider.php

Ticket: https://spryker.atlassian.net/browse/SDK-1606

SDK-1606: New error during the manifest integration

---

composer.json
src/Builder/ClassWriter/ClassFileWriter.php
src/Builder/FileNormalizer/FileNormalizerInterface.php
src/Builder/FileNormalizer/FileNormalizersExecutor.php
src/Builder/FileNormalizer/FileNormalizersExecutorInterface.php
src/Builder/FileNormalizer/PhpCSFixerFileNormalizer.php
src/Builder/FileStorage/FileStorage.php
src/Builder/FileStorage/FileStorageFactory.php
src/Builder/FileStorage/FileStorageInterface.php
src/Executor/ManifestExecutor.php
src/IntegratorFactory.php
tests/SprykerSdkTest/Integrator/Builder/FileNormalizer/FileNormalizersExecutorTest.php
tests/SprykerSdkTest/Integrator/Builder/FileStorage/FileStorageTest.php

Ticket: https://spryker.atlassian.net/browse/PPLUS-1860
Description:
- Added cs fixer file post-processing

PPLUS-1860 add cs fixer file normalizer

---

tests/_data/manifests/src/integrator-manifests-master/Spryker/TestIntegratorConfigureEnv/1.0.4/installer-manifest.json
tests/_data/manifests/src/integrator-manifests-master/Spryker/TestIntegratorConfigureModule/1.0.3/installer-manifest.json
tests/_data/tests_files/test_integrator_configure_env.php
tests/_data/tests_files/test_integrator_configure_env_choices.php
tests/_data/tests_files/test_integrator_configure_module.php

Add test for boolean values in configure module manifests

PPLUS-1186: Add test for boolean values in configure module manifests

---

docs/manifest-types.md

Change log:
- Add missing setting to the documentation

SDK-1609: Add missing setting to the documentation

---

src/ManifestStrategy/ConfigureEnvManifestStrategy.php
tests/SprykerSdkTest/Integrator/IntegratorFacadeTest.php
tests/_data/tests_files/test_integrator_configure_env.php
tests/_data/tests_files/test_integrator_configure_env_choices.php

Ticket: [SDK-1585](https://spryker.atlassian.net/browse/SDK-1585)

SDK-1585: Integrator should check if the configuration index already exists

---

src/Builder/Visitor/AddMethodCallToCallListVisitor.php
tests/_data/manifests/src/integrator-manifests-master/Spryker/TestIntegratorWirePlugin/1.0.2/installer-manifest.json
tests/_data/tests_files/test_integrator_wire_plugin_dependency_provider.php

[SDK-1689](https://spryker.atlassian.net/browse/SDK-1689)

SDK-1689: Wrong integration of the wrapped methods

---

src/Builder/FileNormalizer/CodeSniffStyleFileNormalizer.php
src/Builder/FileNormalizer/FileNormalizersExecutor.php
src/Builder/FileNormalizer/PhpCSFixerFileNormalizer.php
src/Executor/ProcessExecutor.php
src/Executor/ProcessExecutorInterface.php
src/IntegratorConfig.php
src/IntegratorFactory.php
tests/SprykerSdkTest/Integrator/Builder/FileNormalizer/CodeSniffStyleFileNormalizerTest.php
tests/SprykerSdkTest/Integrator/Builder/FileNormalizer/PhpCSFixerFileNormalizerTest.php

Ticket: https://spryker.atlassian.net/browse/SDK-1687

SDK-1687: Call Code Fixer from integrator through the Spryker Command

---

.github/workflows/ci.yml

https://spryker.atlassian.net/browse/SDK-1438

SDK-1438: Update php version in CI

---

composer.json
src/Executor/ManifestExecutor.php
src/FileStorage/BucketFileStorage.php
src/FileStorage/BucketFileStorageInterface.php
src/IntegratorConfig.php
src/IntegratorFactory.php
src/Manifest/FileBucketManifestReader.php
src/Manifest/FileBucketManifestReaderInterface.php
src/Manifest/RepositoryManifestReaderInterface.php
src/Manifest/RepositoryRepositoryManifestReader.php
tests/SprykerSdkTest/Integrator/FileStorage/BucketFileStorageTest.php
tests/SprykerSdkTest/Integrator/Manifest/ManifestReaderTest.php

Ticket: https://spryker.atlassian.net/browse/SDK-1794

SDK-1757: Task 2. Connect S3 buckets

---

src/Executor/ReleaseGroup/DiffGenerator.php
tests/SprykerSdkTest/Integrator/Executor/ReleaseGroup/ReleaseGroupManifestExecutorTest.php

https://spryker.atlassian.net/browse/SDK-1922
* Adjusted logic, integrator uses existing branch and revert after execution to this branch

SDK-1922: Uses existing branch

---

bin/integrator
src/Console/IntegratorLockUpdaterConsole.php
src/Console/ModuleInstallerConsole.php
src/Executor/ManifestExecutor.php
src/Executor/ManifestExecutorInterface.php
src/Executor/Module/ModuleManifestExecutor.php
src/Executor/Module/ModuleManifestExecutorInterface.php
src/Executor/ReleaseGroup/DiffGenerator.php
src/IntegratorFacade.php
src/IntegratorFacadeInterface.php
src/IntegratorLock/IntegratorLockWriter.php
src/Manifest/RepositoryRepositoryManifestReader.php
tests/SprykerSdkTest/Integrator/IntegratorFacadeTest.php

https://spryker.atlassian.net/browse/SDK-1964

SDK-1964: Pre-check integration lock

---

src/Builder/Visitor/AddPluginToPluginListVisitor.php
tests/_data/manifests/src/integrator-manifests-master/Spryker/TestIntegratorWirePlugin/1.0.2/installer-manifest.json
tests/_data/tests_files/test_integrator_wire_plugin_dependency_provider.php

https://spryker.atlassian.net/browse/SDK-2037

SDK-2037: Fix the issue with after and before parameters in 1 manifest

---

src/Executor/ReleaseGroup/DiffGenerator.php

Ticket: https://spryker.atlassian.net/browse/SDK-2083

SDK-2083: Integrator. Display output of composer error

---

src/Builder/Visitor/AddClassToClassListVisitor.php
src/Executor/ManifestExecutor.php
src/Executor/ReleaseGroup/DiffGenerator.php
src/ManifestStrategy/AddConfigArrayElementManifestStrategy.php
src/ManifestStrategy/UnwirePluginManifestStrategy.php
src/ManifestStrategy/WirePluginManifestStrategy.php
tests/SprykerSdkTest/Integrator/Executor/ReleaseGroup/ReleaseGroupManifestExecutorTest.php
tests/_data/manifests/src/integrator-manifests-master/Spryker/TestIntegratorAddConfigArrayElement/1.0.0/installer-manifest.json
tests/_data/project_mock/src/Pyz/Client/TestIntegratorAddConfigArrayElement/TestIntegratorAddConfigArrayElementConfig.php
tests/_data/tests_files/test_integrator_add_config_array_element_config.php

https://spryker.atlassian.net/browse/SDK-1958

SDK-1958: Fixed error message, add element to class method

---

docs/manifest-types.md

Ticket: https://spryker.atlassian.net/browse/SDK-2028

SDK-2024: Updated manifest types documentation

---

src/ConfigReader/ConfigReader.php
src/ConfigReader/ConfigReaderInterface.php
src/ConfigReader/ConfigValuesVisitor.php
src/IntegratorConfig.php
tests/SprykerSdkTest/Integrator/ConfigReader/ConfigReaderTest.php
tests/_data/project_config/config_default.php
tests/_data/project_mock/config/Shared/config_default.php
tests/_data/tests_files/test_integrator_configure_env.php
tests/_data/tests_files/test_integrator_configure_env_choices.php

https://spryker.atlassian.net/browse/SDK-2013

SDK-2013: Config reader

---

src/Builder/ClassModifier/CommonClass/CommonClassModifier.php
src/Builder/Comparer/ClassConstExpressionCompareStrategy.php
src/Builder/Comparer/CompareStrategyInterface.php
src/Builder/Comparer/NodeComparer.php
src/Builder/Comparer/NodeComparerFactory.php
src/Builder/Comparer/NodeComparerInterface.php
src/Builder/Comparer/UnsupportedComparerNodeTypeException.php
src/Builder/Finder/UseStatementsFinder/UseStatementVisitor.php
src/Builder/Finder/UseStatementsFinder/UseStatementsFinder.php
src/Builder/Finder/UseStatementsFinder/UseStatementsFinderInterface.php
src/Builder/Visitor/AddStatementToStatementListVisitor.php
tests/SprykerSdkTest/Integrator/Builder/Comparer/ClassConstExpressionCompareStrategyTest.php
tests/SprykerSdkTest/Integrator/Builder/Comparer/NodeComparerTest.php
tests/_data/manifests/src/integrator-manifests-master/Spryker/TestIntegratorConfigureModule/1.0.3/installer-manifest.json
tests/_data/project_mock/src/Pyz/Zed/TestIntegratorDefault/TestIntegratorDefaultConfig.php
tests/_data/tests_files/test_integrator_configure_module.php

https://spryker.atlassian.net/browse/SDK-2035

SDK-2035: Module configuration fix

---

src/Builder/Visitor/RemovePluginFromPluginListVisitor.php
tests/_data/manifests/src/integrator-manifests-master/Spryker/TestIntegratorUnwirePlugin/1.0.3/installer-manifest.json
tests/_data/project_mock/src/Pyz/Zed/TestIntegratorUnwirePlugin/TestIntegratorUnwirePluginDependencyProvider.php
tests/_data/tests_files/test_integrator_unwire_plugin_dependency_provider.php

https://spryker.atlassian.net/browse/SDK-2143

SDK-2143: Fix unwire plugin issue

---

src/Builder/Creator/MethodStatementsCreator.php
src/Executor/ReleaseGroup/DiffGenerator.php
src/VersionControlSystem/GitRepository.php
tests/SprykerSdkTest/Integrator/Executor/ReleaseGroup/ReleaseGroupManifestExecutorTest.php
tests/_data/manifests/src/integrator-manifests-master/Spryker/TestIntegratorConfigureModule/1.0.3/installer-manifest.json
tests/_data/tests_files/test_integrator_configure_module.php

https://spryker.atlassian.net/browse/SDK-2518

SDK-2518: Fixed a few issue releated to RG

---

src/Executor/ReleaseGroup/DiffGenerator.php
tests/SprykerSdkTest/Integrator/Executor/ReleaseGroup/ReleaseGroupManifestExecutorTest.php

https://spryker.atlassian.net/browse/SDK-2573

SDK-2573: Remove double clean branch and fixed commit changes if it has

---

src/Builder/Visitor/AddPluginToPluginListVisitor.php
tests/_data/manifests/src/integrator-manifests-master/Spryker/TestIntegratorWirePlugin/1.0.2/installer-manifest.json
tests/_data/project_mock/src/Pyz/Zed/TestIntegratorWirePlugin/TestIntegratorWirePluginDependencyProvider.php
tests/_data/tests_files/test_integrator_wire_plugin_dependency_provider.php

https://spryker.atlassian.net/browse/SDK-2040

SDK-2040 fix already added plugins issue

---

src/Builder/Printer/ClassPrinter.php
tests/_data/manifests/src/integrator-manifests-master/Spryker/TestIntegratorConfigureModule/1.0.3/installer-manifest.json
tests/_data/project_mock/src/Pyz/Zed/TestIntegratorDefault/TestIntegratorDefaultConfig.php
tests/_data/tests_files/test_integrator_configure_module.php

https://spryker.atlassian.net/browse/SDK-2437

SDK-2437: Fixed backslash in string, added tests

---

.github/workflows/trigger-remote-pr.yml

https://spryker.atlassian.net/browse/SDK-1805

SDK-1805 CI automation.

---

composer.json
src/IntegratorFactory.php
src/ManifestStrategy/AbstractWireXmlManifestStrategy.php
src/ManifestStrategy/WireSchemaManifestStrategy.php
src/ManifestStrategy/WireTransferManifestStrategy.php
tests/SprykerSdkTest/Integrator/IntegratorFacadeTest.php

https://spryker.atlassian.net/browse/SDK-2506

SDK-2506 Integrator xml strategies

---

src/Manifest/RepositoryRepositoryManifestReader.php
tests/SprykerSdkTest/Integrator/BaseTestCase.php

https://spryker.atlassian.net/browse/SDK-2902

SDK-2902: Fixed archive manifests path

---

composer.json
src/Builder/Creator/MethodCreator.php
src/IntegratorFactory.php

https://spryker.atlassian.net/browse/SDK-2704

SDK-2704: wrong return type and stms

---

composer.json
src/ManifestStrategy/GlossaryManifestStrategy.php

https://spryker.atlassian.net/browse/SDK-2896

SDK-2896: Wrap to quotes glossary values

---

composer.json
src/Builder/Creator/AbstractReflectionClass.php
src/Builder/Creator/MethodCreator.php
src/Builder/Visitor/AddPluginToPluginListVisitor.php

https://spryker.atlassian.net/browse/SDK-2707

SDK-2707: Fixed integration cases related to structure

---

composer.json
src/Builder/ClassModifier/ClassConstant/ClassConstantModifier.php
src/ManifestStrategy/ConfigureModuleManifestStrategy.php

https://spryker.atlassian.net/browse/SDK-2544

SDK-2544 fix empty array module config

---

docs/README.md
docs/manifest-action-types.md

Task: https://spryker.atlassian.net/browse/SDK-2953

SDK-2953 Renamed manifest-type to manifest-action-type

---

composer.json
src/Builder/ClassModifier/ClassInstanceModifierStrategy/Wire/ReturnClassWireClassInstanceModifierStrategy.php
src/Builder/Creator/MethodCreator.php
src/Builder/Creator/MethodCreatorInterface.php
src/IntegratorFactory.php

https://spryker.atlassian.net/browse/SDK-4486

SDK-4486: Fixed return type for single return

---

bin/integrator

Ticket: https://spryker.atlassian.net/browse/SDK-4659

SDK-4659: Integrator remove project autoload

---

src/Builder/ClassLoader/ClassLoader.php

https://spryker.atlassian.net/browse/SDK-4675

SDK-4675: Fixed issue

---

src/Builder/FileNormalizer/CodeSniffStyleFileNormalizer.php
src/Builder/FileNormalizer/CodeSnifferCompositeNormalizer.php
src/Builder/FileNormalizer/FileNormalizerInterface.php
src/Builder/FileNormalizer/FileNormalizersExecutor.php
src/Builder/FileNormalizer/PhpCSFixerFileNormalizer.php
src/IntegratorFactory.php
tests/SprykerSdkTest/Integrator/Builder/FileNormalizer/CodeSniffStyleFileNormalizerTest.php
tests/SprykerSdkTest/Integrator/Builder/FileNormalizer/CodeSnifferCompositeNormalizerTest.php
tests/SprykerSdkTest/Integrator/Builder/FileNormalizer/FileNormalizersExecutorTest.php
tests/SprykerSdkTest/Integrator/Builder/FileNormalizer/PhpCSFixerFileNormalizerTest.php

https://spryker.atlassian.net/browse/SDK-4637

SDK-4637 fix file normalizers

---

src/ManifestStrategy/GlossaryManifestStrategy.php
tests/SprykerSdkTest/Integrator/IntegratorFacadeGeneralTest.php

https://spryker.atlassian.net/browse/SDK-4180

SDK-4180 fix eol in csv

---

resources/phpcs.xml
src/Builder/FileNormalizer/CodeSnifferCompositeNormalizer.php
src/Composer/ComposerLockReader.php
src/Composer/ComposerLockReaderInterface.php
src/IntegratorFactory.php
tests/SprykerSdkTest/Integrator/Builder/FileNormalizer/CodeSnifferCompositeNormalizerTest.php

https://spryker.atlassian.net/browse/SDK-4641

SDK-4641 creation of the missed phpcs.xml 

---

composer.json
src/Builder/Visitor/AddPluginToPluginListVisitor.php

https://spryker.atlassian.net/browse/SDK-2855

SDK 2855 add missed plugin classes

---

src/Console/DiffGenerateConsole.php
src/Executor/ReleaseGroup/DiffGenerator.php
src/Transfer/IntegratorCommandArgumentsTransfer.php
tests/SprykerSdkTest/Integrator/Console/DiffGenerateConsoleTest.php
tests/SprykerSdkTest/Integrator/Executor/ReleaseGroup/ReleaseGroupManifestExecutorTest.php

https://spryker.atlassian.net/browse/SDK-4712

SDK-4712: approved manifest rating

---

src/VersionControlSystem/GitRepository.php

SDK-5590: Ignore empty lines in diff

---

composer.json

Ticket: https://spryker.atlassian.net/browse/SDK-5624

SDK-5624 Updated spryker-sdk/utils dependency.

---

composer.json
composer.lock

https://spryker.atlassian.net/browse/SDK-5711

SDK-5711: updated composer

---

.github/workflows/trigger-remote-pr-in-release-app.yml
.github/workflows/trigger-remote-pr-in-upgrader.yml
src/Builder/Extractor/ValueExtractor/AbstractValueExtractorStrategy.php

https://spryker.atlassian.net/browse/FRW-7460

FRW-7460: Fixed multitype in AbstractValueExtractorStrategy, Updated CI

---

src/Builder/Extractor/ValueExtractor/AbstractValueExtractorStrategy.php

https://spryker.atlassian.net/browse/FRW-7460

FRW-7460: Fixed multitype in AbstractValueExtractorStrategy

---

.github/workflows/ci.yml
phpunit.xml.dist

Ticket: https://spryker.atlassian.net/browse/FRW-10059
Enabled Phpunit code coverage reports in the CI.

FRW-10059 Enable code coverage reports.
